import { faker, fakerFR } from "@faker-js/faker";
import { CardEventInterface } from "../../services/interfaces/event";

export const eventDiscipline = [
  "Mathématiques",
  "Arts plastiques",
  "Français",
  "Anglais",
  "Physique",
  "Musique",
  "histoire",
  "Technologie",
  "Chimie",
  "Education-civique",
  "Philosophie",
  "Biologie",
];

const fakerEvents: CardEventInterface[] = [
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },

  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },

  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },

  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },

  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
];

export const fakerEventsData = {
  datas: fakerEvents,
};

const fakerUserEvents: CardEventInterface[] = [
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },

  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },

  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "children", true),
    avatar_name: faker.image.people(),
    location: fakerFR.location.city(),
    tags: ["anniversaire", "Cagnotte"],
  },
  {
    name: faker.person.fullName(),
    title: faker.lorem.words(),
    description: faker.lorem.paragraphs(),
    date: faker.date.future(),
    image: faker.image.imageUrl(300, 300, "sports", true),
    avatar_name: faker.image.avatarLegacy(),
    location: fakerFR.location.city(),
    tags: ["sortie", "pierre"],
  },
];

export const fakerUserEventsData = {
  datas: fakerUserEvents,
};

const fakerTypeEvents: string[] = ["Public", "Privé"];

export const fakerTypeEventsData = {
  datas: fakerTypeEvents,
};

const fakeEventTags: string[] = [
  "Cagnotte",
  "Sport",
  "Parc",
  "Sortie",
  "Fête",
  "Musique",
  "Association",
  "Cours",
  "Sondage",
  "Covoiturage",
  "Musée",
  "Devoir",
  "foot",
];
export const fakerEventTagsData = {
  datas: fakeEventTags,
};
